# on: [push]

# jobs:
#   test-gcp:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - id: 'auth'
#         uses: 'google-github-actions/auth@v1'
#         with:
#           credentials_json: '${{ secrets.GCLOUD_API_KEYFILE }}'

#       - name: 'Set up Cloud SDK'
#         uses: 'google-github-actions/setup-gcloud@v1'

#       - name: 'Use gcloud CLI'
#         run: 'gcloud info'
